name: Keep App Alive

on:
  schedule:
    # Runs every 5 minutes from 06:00 UTC to 11:55 UTC
    # (07:00 CET to 12:55 CET)
    - cron: '*/5 6-11 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: curl -I https://forex-robot-u7sx7cbkeyn3xmtggnqpzw.streamlit.app/
